Upon deploying my App with Espresso tests on CircleCI I get "No configuration" and "No Tests" error. The Espresso tests are working fine locally on Android Studio.

With a commit, CI job runs and fails with "No config found" error. details of the error is as follows:

#!/bin/sh -eo pipefail
#No configuration was found in your project. Please refer to https://circleci.com/docs/2.0/ to get started with your configuration.
false
Exited with code 1
When I manually setup and build the project on Circle-CI I see it's progressing from Starting the build--> Start Container -->Enable SSH -->Restore source cache --> Checkout using deploy key xxx till Disable SSH, and then it shows "NO TESTS" Error.

Below is my .circleci/config.yml

version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-27;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-16;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
          background: true
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Run EspressoTests
          command: ./gradlew connectedAndroidTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results